# Hardware and Software

## Learning Objectives

After studying this chapter, you should be able to:

* Explain the organization of a computing system and understand the relationships and interactions between hardware components.
* Define the general functions and identify key hardware components, including central processing units (CPUs), memory, and input and output devices.
* Describe the functions of the different types of software, mainly the operating systems, applications, and utilities.
* Understand fundamental programming concepts, such as algorithms, variables, control structures, and data types.
* Identify different embedded and computer systems and understand their significance in the digital world.
* Explain the symbiotic relationship between hardware and software in computing systems.
* Illustrate how hardware capabilities influence software design and vice versa.

## Introduction

As we study information science, it is essential to establish a comprehensive understanding of the fundamental technologies inherent to information systems. This chapter serves as a guide to explore a computing system, particularly the computer system, with a central focus on its two primary categories: hardware and software. This foundational knowledge serves as the prerequisite to discern the intricate functions that govern digital information. 

By exploring the specifics of hardware and software, we pave the way to identify potential innovations and improvements. As these technological components form the backbone influencing the landscape of information science – without the nuanced understanding of these fundamental elements, our ability to navigate and contribute meaningfully to the advancements in digital information would be constrained.

When we talk about computers, our minds naturally conjure up images of tangible elements such as a monitor, a keyboard, a mouse, and other electronic components neatly enclosed within a rectangular casing. To put it simply, this is what we call Hardware. To give it a proper definition, the hardware refers to the physical components of an analog or digital computer system or electronic devices. These are the machinery, circuits, and devices that constitute the computer’s physical structure and enable it to function. While we commonly associate hardware with personal computers, it actually permeates an extensive array of computing systems and electronic devices such as mobile devices, point-of-sale devices, self-service checkout machines, automated kiosks, gaming consoles, medical devices, and others.
 
Yet, these components and devices are merely manufactured silicon, aluminum, or copper. There exists a crucial counterpart to this physicality: the Software. It is the software of a system that breathes life into these mechanical structures, transforming it to dynamic and intelligent tools. Software refers to the intangible set of instructions, programs, or data that tells the computing system to execute specific tasks or operations. It comes into the form of code written in programming languages, applications, operating systems, and other system utilities. A computing device can only properly function when both hardware and software work together.

The sophisticated nature of a computer system makes it difficult to fully understand from the outset. A key to it is to look into the hierarchical nature inherent in complex systems. This hierarchical system refers to the arrangement of interrelated subsystems in a structured hierarchy or top-down layers. Think of it as a set of nested categories, starting with a general category at the top and becoming more specific as you go down. This way of organizing is helpful in defining its design and description. The overarching concepts can be systematically dissected and streamlined individually, contingent upon the specific level under consideration. At each level, the focus is directed towards two essential aspects: the structure and the function. Structure is defined as the arrangement and interrelationship of components within the system. It is the spatial configuration or organizational framework that tells how different parts of a system interact. Function is defined as the role of each individual component within the system. It is the operations, activities, or tasks that the individual component performs. 

Now that we understand how systems are generally organized, let us dive into the actual basics. This chapter will cover key concepts, including:

* Hardware
  + Internal Hardware
  + Computer Architecture and Organization
  + Input and Output Devices
* Software
  + Operating Systems
  + Middleware
  + Applications
  + Programming Languages
* Computer Systems
* Embedded Systems

In general, a computer system can perform four (4) basic functions:

1. Data processing involves the collection of data into the system and the conversion of it into functional information for the system to utilize. 
2. Data storage is the organized storing or holding of data within the system enabling the system or user to retrieve it when needed. 
3. Data movement is the process of transporting data from one location to another, facilitating communication.
4. Control manages the flow of data and execution of instructions between different components of the system.

To enable the computer to execute these functions seamlessly, it relies on a set of integral structural components. A traditional computer with a single processor has four (4) main ones:

1. A central processing unit (CPU), or processor, which controls the operation of a computer and processes the data to execute the instructions for the system to function. It is the core element that drives the computational capabilities of a computer.
2. Main memory refers to the electronic storage where data and instructions are stored for processing. 
3. Input and output devices, collectively referred to as I/O, communicate the data or signal between a computer system and its external environment. 
    i) Input refers to the data received by the computer, while 
    i) Output refers to the data that the computer sends to its external devices.
4. System interconnection refers to the physical links that connect various components within a computer system, enabling them to communicate and work together. 
    i) A system bus is a communication system that consists of conducting wires with all other components attached to it to transmit data within the computer. 
    i) A networking infrastructure is also a type of system interconnection that allows multiple systems to communicate with each other.

These components form the internal and external elements of a computer, with the internal parts referred to as components and the external hardware components known as peripherals. There may be one or more of each of these components. If there is more than one processor, then it is called a multicore computer. 

5. A core is added to its structure which consists of all the processors inside a single chip. 
6. Multicore computers also use multiple layers or memory called cache. This is a smaller version of the main memory, enabling the system to access data faster than storing it in the main memory.

Let’s look into probably the most complex component, which is the CPU. The main structure of the CPU consists of the following units:

1. The control unit manages the overall operations of the CPU, processing the data and executing the instructions.
2. The arithmetic and logic unit (ALU) performs the actual data processing of the system i.e. the arithmetic (addition, subtraction, multiplication, and division) and logical (AND, OR, NOT, XOR) operations. 
3. The registers are what serves as the internal storage of the CPU.
4. CPU interconnection is the communication between the mechanisms within the CPU. 

```{mermaid}
flowchart LR
  A[Computer] --> B(CPU)
  B --> D(ALU)
  D --> C[Control Unit]
```

Now that we've delved into the intricacies of computer organization, let's shift our focus to the broader components that constitute it. Let’s examine the contents contained within the confines of the rectangular casing, such as: 
1. The motherboard is a printed circuit board (PCB) that contains the CPU and all other components, serving as the main hub for the computer.
2. The CPU, as aforementioned, is the core of the computer’s processes to execute instructions.
3. To facilitate the storage and preservation of the memory, the computer has three (3) primary components:

* Random access memory (RAM) is essentially the volatile memory of the computer. Memory is temporarily stored here for quick access and easy manipulation. When the computer powers off, data is cleared. 
* Solid state drive (SSD) is a non-volatile memory, but it uses flash memory to provide quick access to frequently used data. This memory is still stored even when the computer is powered off.
* Hard drive is also a non-volatile memory that is high-capacity for long-term data retention. Files, documents, or applications are stored in this physical drive. 

4. Graphic Processing Units, Network Interface Cards, ports, power supplies, transistors, and chips, all of which fall under the umbrella of internal hardware.


For the components to effectively acquire data to process and present information, peripheral devices, or external hardware. These are the I/O devices that serve as conduits for the exchange of data. 
Common input devices include:

1. A keyboard is used to input text, numbers, special characters, and commands. It has a set of keys that represent a character, symbol, or function such as navigation (up, down, left, right), modifier (shift, ctrl, cmd, alt), or others (media playback, brightness, etc)
2. A mouse is a pointing device that provides the user to navigate the interface and interact with elements with a cursor. 
3. Microphones, cameras, touchpads, flash drives, and memory cards are also examples of input devices.

Common output devices include:

1. A monitor is a device akin to a television screen to display information graphically generated by the computer system. 
2. A printer renders digital data into printed material.
3. A speaker serves as an audio output device.
